### ISSUE TITLE
Not quite understanding

### ISSUE THREAD

**Issue by scargill** [TotallyInformation/node-red-example-debug#2]
Right.... added the subflow, added the flow, got MQTT with sockets - page :1880/debug  is coming up reading "Node-Red Debug Page" - send something to /debug/test   - nothing happens. Am I missing out something?

**Comment by scargill** [comment]
Oh, I've just realised - in the first function is a reference to an mqtt broker (clearly we put our own in there - but no reference to a username and password.... where would you put that... and is the rest compatible with local Mosquitto with websockets?

**Comment by TotallyInformation** [comment]
Hi Peter, no real security in it as it stands I'm afraid. As long as you have Mosquitto with websockets, that is fine.

**Comment by scargill** [comment]
WhaT I meant was – I can’t use it with my Mosquitto with websockets as it will be expecting username and passwords?

Also can you point me to where to get the bits I mentioned and where is the base to store them?

I’m really quite excited to have potentially a second screen for debug…

Pete.

**Comment by TotallyInformation** [comment]
Ah, sorry. You specify the id and password in the config object for the Paho client. I will look it up in a sec.

OK, if you look in the script1 template node, you will see the details and links to the Paho project which has both the download and the information.

In the output_template node, you will see existing links to JQuery from cdnjs then references to 2 local js files. These need to go into the folder you have designated as your static content folder in the Node-Red settings. A bit different for me as I don't install NR globally as Nick/Dave recommend (for reasons I've mentioned before). So I can just do this to configure Express to serve static content:

```
// Add a simple route for static content served from './public'
app.use( "/", express.static("public") );
```

Instead, you need to use the setting "httpStatic", point it to a folder under the home of your NR config - `/home/pi/.nodered` ? I can never work all that out, much to complicated.

Hope that does it for you.

**Comment by TotallyInformation** [comment]
Here is the link to the Paho config:

http://www.eclipse.org/paho/files/jsdoc/symbols/Paho.MQTT.Client.html#connect

```
{string} connectOptions.userName
- Authentication username for this connection.
{string} connectOptions.password
- Authentication password for this connection.
```

**Comment by TotallyInformation** [comment]
In situ in the `script1` template node:

```
    // @see http://www.eclipse.org/paho/files/jsdoc/symbols/Paho.MQTT.Client.html#connect
    var options = {
        timeout: 3,
        //userName: "xxxxx",
        //password: "xxxxx",
        //useSSL: useTLS,
        cleanSession: true,
        onSuccess: onConnect,
        onFailure: onConnectionLost
    };
```

**Comment by TotallyInformation** [comment]
I've added some clarifications and copies of code for the two template nodes to this repo.

**Comment by scargill** [comment]
Do you think I’ve missed something as it has made ZERO difference..
1. ```
     I’ve added in username and password as you have suggested – also checked the port number was right.
   ```
2. ```
     I’ve grabbed the two files – mqttws31.js and jquery-animate-shadow-min.js, created a js directory under .node-red and shoved the files in there (my .node-red directory is at /home/pi/.node-red)
   ```

Any thoughts? So near yet so far…

**Comment by TotallyInformation** [comment]
If you open dev tools in your browser, then refresh the page, do you get any errors?

**Comment by scargill** [comment]
Ok, good call..

It can’t find ANY of the javascript – and I just realised I’m missing one of them anyway  - the bower stuff – where do you get that from??

So typically not found http://192.168.0.20:1880/js/mqttws31.js

So two problems – no bower tools and /user/pi/.node-red clearly is not the place to put the /js/ folder…

**Comment by scargill** [comment]
Oh and this is the state of my settings.js file – both commented out..

```
// By default, the Node-RED UI is available at http://localhost:1880/

// The following property can be used to specifiy a different root path.

// If set to false, this is disabled.

//httpAdminRoot: '/admin',



// When httpAdminRoot is used to move the UI to a different root path, the

// following property can be used to identify a directory of static content

// that should be served at http://localhost:1880/.

//httpStatic: '/home/nol/node-red-dashboard/',
```

**Comment by TotallyInformation** [comment]
I don't believe you need Modernizr so just comment it out. You don't really need the animate library either.

I think you might have to ask Nick/Dave about the location of static data unless there is something in the docs. I'll have a quick search.

**Comment by TotallyInformation** [comment]
Ah, OK, you need to put in an absolute folder to the settings. Something like:

```
/home/pi/.node-red/public
```

Will allow you to put files in there. Note that I created a subfolder "js/" in public.

So the URL "`http://localhost:<nrport>/js/mqtt.js`" will actually need to exist in "`/home/pi/.nodered/public/js/mqtt.js`".

Now you know why I use the embedded form. That way, you know EXACTLY where everything is every time.

**Comment by scargill** [comment]
Nearly there – so I was getting 2 errors in the debug

One was missing mqttws31.js file -  I put in an httpstatic address without changing anything else in the setup – and the missing js message has disappeared – the other issue remains

```
            // Create a client instance

            var mqtt = new Paho.MQTT.Client( location.127.0.0.1, 9001, "web_" + parseInt(Math.random() * 100, 10) );



            // @see http://www.eclipse.org/paho/files/jsdoc/symbols/Paho.MQTT.Client.html#connect
```

There is a red X next at the end of that first line and the message says “uncaught syntax error missing ) after argument list…

Sadly I am looking at that line as you are and there is nothing missing unless I’m going blind//

**Comment by TotallyInformation** [comment]
The bit that is showing `location.127.0.0.1` should be `location.hostname` which is a built-in browser variable. Can you try putting `console.log(location.hostname)` into your browsers console? See what comes back. it should either say "localhost" or "127.0.0.1"

**Comment by scargill** [comment]
Moving on – of course you have to put a string for the mqtt server - duh – and that still didn’t work – then I realised the page is executing on the PC, not the PI!!!

And of course I’d missed all the “not connecting” messages.

var mqtt = new Paho.MQTT.Client( "127.0.0.1", 9001, "web_" + parseInt(Math.random() \* 100, 10) );

var mqtt = new Paho.MQTT.Client( "192.168.0.20", 9001, "web_" + parseInt(Math.random() \* 100, 10) );

And then there were no error messages – WHEEEEE.

But sending “just some text here” to “debug/morestuff” didn’t work then I remembered this is all case sensitive and so I sent to

DEBUG/morestuff

And… IT ALL WORKS – you are SO clever!

Erm, given a fixed heading like DEBUG/morestuff – I note that the content over-writes the previous content… any way to modify that to ADD to the content??? like a normal debug?? Or am I missing the point…

Pete.

**Comment by TotallyInformation** [comment]
Phew, we got there. However, you really should leave that command with `location.hostname` in it because that's the clever bit :-)  Of course, that assumes your MQTT broker is on the same host as your Node-Red instance.

In my own setup, I actually pass the IP addresses and ports of the broker and NR into the global variables so that they can be passed down to things like this.

Anyway, in regard to the heading - yes, that is deliberate. So whenever you send a message with the same topic, it overwrites the previous entry - otherwise, if you left it for a while, you would have a enormous page showing!

So all you need to do is make sure that whatever `msg` you send includes a suitable `msg.topic`. It doesn't have to start with "DEBUG" either, that is just the default that gets added if you don't send a topic.

**Comment by TotallyInformation** [comment]
Example output I just sent with a simple inject node:

```
MyDebug

Last Update: Sat Mar 19 2016 21:20:18 GMT+0000 (GMT Standard Time)

{
  "topic": "DEBUG/MyDebug",
  "payload": "test",
  "_msgid": "d9f8b777.260748"
}
```

**Comment by TotallyInformation** [comment]
Sorry, slight correction to the last but one post.

The sub-flow actually _adds_ "DEBUG/" to the start of your `msg.topic`. This is used because we are sending the debug data via MQTT and if we didn't add something unique on the front, you would end up overwriting other MQTT topics. In addition, the web page wouldn't know what to listen for.

Anyway, the point is that you can send the same topic over an over and you only get a single entry in the output but it updates the last update timestamp. This is the same as using MQTT of course. In fact, the debug example is a simple MQTT web client you could adapt for listening to other topics.

**Comment by scargill** [comment]
I hope I’ve done a suitable job of promoting your tool!

http://tech.scargill.net/to-weather-or-not-to-weather/

From: Peter Scargill [mailto:pete@scargill.org] 
Sent: 19 March 2016 21:18
To: 'TotallyInformation/node-red-example-debug' reply@reply.github.com; 'TotallyInformation/node-red-example-debug' node-red-example-debug@noreply.github.com
Subject: RE: [node-red-example-debug] Not quite understanding (#2)

Moving on – of course you have to put a string for the mqtt server - duh – and that still didn’t work – then I realised the page is executing on the PC, not the PI!!!

And of course I’d missed all the “not connecting” messages.

var mqtt = new Paho.MQTT.Client( "127.0.0.1", 9001, "web_" + parseInt(Math.random() \* 100, 10) );

var mqtt = new Paho.MQTT.Client( "192.168.0.20", 9001, "web_" + parseInt(Math.random() \* 100, 10) );

And then there were no error messages – WHEEEEE.

But sending “just some text here” to “debug/morestuff” didn’t work then I remembered this is all case sensitive and so I sent to

DEBUG/morestuff

And… IT ALL WORKS – you are SO clever!

Erm, given a fixed heading like DEBUG/morestuff – I note that the content over-writes the previous content… any way to modify that to ADD to the content??? like a normal debug?? Or am I missing the point…

Pete.

**Comment by TotallyInformation** [comment]
Thanks Peter. Interesting about the weather. I need to rework the weather section of my home automation hub. The problem with Sheffield is that it is chock full of micro-climates and the nearest full weather station is the ex-RAF base in Lincolnshire which is on the coastal plane and 600ft lower than us!

**Comment by scargill** [comment]
I’ve JUST updated the blog again as I realised I was converting the data to JSON when the HTTP node can do that for you – and that your code can ALL be shoved into the subflow to tidy up. Thanks for that. My next job is to update my Nextion displays so I can put in the external weather for Hexham and our place in Spain.  Yes in Spain (Galera) we have a micro-climate – we can sit and watch thunder and lightning over the hills in the next town (Huescar) and we almost always miss it!  Where as here in Bellingham, Northumberland it is almost always raining :)

Pete.

**Comment by scargill** [comment]
Question Julian

I’ve been playing with this debugger how for a while – I have the output of forecast.io going to it via a simple function node..

msg.topic="england_weather";

return msg;

So I have one which says Spanish_weather and the other that says England-weather…. Those outputs also go to a normal debug just to check they are actually putting something out. . For the life of me – the english one is not producing anything in the debugger (yours) but the Spanish one is – the only difference might be a slight difference in size (lots of output) or special characters… it WAS working.. but today I can repeatedly test both – only the Spanish one is producing output on the debugger (along with any test messages I might send…

Ie..

msg.topic=”test1”;

msg.payload=”testing”;

Are you aware of any length restrictions or special characters that might stop any output??

Very frustrating…

Pete.

**Comment by TotallyInformation** [comment]
@scargill Can't think of a specific reason. I'm certainly sending some gig data, try the msg.res from an http in node for example. Maybe try removing spaces and dashes from the topic?
